[package]
name = "lightswitch"
version = "0.1.0"
edition = "2021"

[dependencies]
gimli = "*"
object = "*"
memmap2 = "*"
lazy_static = "*"
anyhow = "*"
thiserror = "*"
libbpf-rs = {version = "*", features=["static"]}
num_cpus = "*"
perf-event-open-sys = "*"
libc = "*"
errno = "*"
plain = "*"

[build-dependencies]
bindgen = "*"
libbpf-cargo = "*"
