name: CI
on:
  pull_request:
  push:

jobs:
  tests:
    runs-on: ubuntu-22.04
    permissions:
        id-token: write
        contents: read
    steps:
    - uses: actions/checkout@main
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Run `cargo check`
      run: nix develop --command cargo check